### ISSUE TITLE
Users should be instructed to create AWS-related secret before starting the controller

### ISSUE THREAD

**Issue by ldimaggi** [sorenmat/k8s-rds#54]
Users should be instructed to create an AWS-related secret, before performing this action:
```
kubectl apply -f deploy/deployment-rbac.yaml
```
The secret to create should take this form (users must supply their own AWS KEY and KEY_ID):
```
apiVersion: v1
kind: Secret
metadata:
  name: k8s-rds
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ##################################
  AWS_SECRET_ACCESS_KEY: #################################
```
