### ISSUE TITLE
Users should be instructed to edit deployment RBAC file to point to their own OpenShift cluster region

### ISSUE THREAD

**Issue by ldimaggi** [sorenmat/k8s-rds#55]
Small point - users may overlook the need to modify deploy/deployment-rbac.yaml to point to their OpenShift region - it would be helpful to remind them to do this before starting the controller. Thanks!

```
    spec:
      containers:
      - image: sorenmat/k8s-rds:latest
        env:
        - name: AWS_REGION
          value: us-east-1   <----  User must update
        - name: AWS_ACCESS_KEY_ID
```
